"""
Auto-generate rclone.conf sections for every document library on a
SharePoint site, so you never add drive_id entries by hand.

Usage: sp2rclone [-s SETTINGS_DIR] [-o OUTPUT]
"""

import re
import sys

from api import get_site_id, get_token, list_drives
from settings import (
    get_sharepoint_settings,
    parse_args,
    resolve_output_path,
    resolve_settings_dir,
)

HEADER = (
    "# Auto-generated by sp2rclone - do not hand-edit drive_id values.\n"
    "# NOTE: credentials are embedded directly in each section below for\n"
    "# ease of local testing. For production, remove client_id/client_secret/\n"
    "# tenant from each section and instead export:\n"
    "#   RCLONE_ONEDRIVE_CLIENT_ID / RCLONE_ONEDRIVE_CLIENT_SECRET / RCLONE_ONEDRIVE_TENANT\n"
    "# so the secret isn't duplicated in plaintext across all sections.\n\n"
)


def slugify(name):
    """Turn a library name into a safe rclone remote/section name."""
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", name).strip("-").lower()
    return f"sp-{slug}" if slug else "sp-unnamed"


def build_sections(drives, tenant_id, client_id, client_secret):
    """Return (sections, mapping) with one rclone section per drive.

    mapping holds (section_name, library display name, webUrl) tuples.
    """
    used_names = set()
    sections = []
    mapping = []

    for d in drives:
        display_name = d.get("name", "unnamed")
        section = slugify(display_name)
        base_section = section
        i = 2
        while section in used_names:
            section = f"{base_section}-{i}"
            i += 1
        used_names.add(section)

        sections.append(
            f"[{section}]\n"
            "type = onedrive\n"
            f"client_id = {client_id}\n"
            f"client_secret = {client_secret}\n"
            f"tenant = {tenant_id}\n"
            "client_credentials = true\n"
            "region = global\n"
            f"drive_id = {d.get('id')}\n"
            "drive_type = documents\n"
        )
        mapping.append((section, display_name, d.get("webUrl", "")))

    return sections, mapping


def build_combine_section(mapping):
    """One [sp-all] remote that exposes every library under its real name."""
    upstreams = " ".join(
        f'"{display_name}={section}:"' for section, display_name, _ in mapping
    )
    return f"[sp-all]\ntype = combine\nupstreams = {upstreams}\n"


def main(argv=None):
    args = parse_args(argv)
    settings_path = resolve_settings_dir(args.settings_dir)
    settings = get_sharepoint_settings(settings_path)
    if not settings:
        sys.exit(1)

    output_path = resolve_output_path(args.output, settings_path)

    site_host = settings["host_name"]
    site_path = settings["site_name"]

    print("Authenticating...")
    token = get_token(
        settings["tenant_id"], settings["client_id"], settings["client_secret"]
    )

    print(f"Resolving site {site_host}{site_path} ...")
    site_id = get_site_id(token, site_host, site_path)

    print("Listing document libraries...")
    drives = list_drives(token, site_id)
    print(f"Found {len(drives)} drive(s).\n")

    sections, mapping = build_sections(
        drives, settings["tenant_id"], settings["client_id"], settings["client_secret"]
    )

    with open(output_path, "w") as f:
        f.write(HEADER)
        f.write("\n".join(sections))
        f.write("\n\n# Combined view of every library - mount THIS remote only.\n")
        f.write(build_combine_section(mapping))

    manifest_path = output_path + ".manifest.tsv"
    with open(manifest_path, "w") as f:
        f.write("section\tlibrary_name\tweb_url\n")
        f.writelines(
            f"{section}\t{display_name}\t{weburl}\n"
            for section, display_name, weburl in mapping
        )

    print(f"Wrote {len(sections)} sections to {output_path}")
    print(f"Wrote human-readable mapping to {manifest_path}")


if __name__ == "__main__":
    main()
